// apps/dashboard/src/components/shared/navbar.tsx
"use client";
import React from "react";
import Link from "next/link";
import DashboardButton from "../ui/dashboardButton";
import NavbarProfileButton from "../ui/NavbarProfileButton";
import Image from "next/image";
import dashboard from "@/lib/assets/dashboard";
import { Dashboard, Misc, News, Notification } from "../icons/icons";
import { AppRoutes } from "@/lib/routes";
import { usePathname } from "next/navigation";
import { cn } from "@/lib/utils";
import { ProfileIcon } from "./profile-icon";

const links = [
  {
    id: 1,
    label: "Dashboard",
    icon: Dashboard,
    href: AppRoutes.dashboard.path,
  },
  { id: 2, label: "News", icon: News, href: AppRoutes.news.path },
];

interface INavLink {
  label: string;
  href: string;
  icon: React.JSX.Element;
  active: boolean;
}

function NavLink(props: INavLink) {
  const { href, label, icon, active } = props;
  return (
    <Link href={href}>
      <div className="flex items-center gap-2">
        {icon}
        <p
          className={cn(
            "leading-[1.35] text-base",
            active ? "text-white" : "text-[#9b9b9b]"
          )}
        >
          {label}
        </p>
      </div>
    </Link>
  );
}

export const Navbar = () => {
  const pathName = usePathname();

  return (
    <nav className="bg-[#0C0C0C] border-b border-[#161616] py-4 px-10 flex items-center">
      <div className="mx-auto flex justify-between items-center w-full">
        {/* Logo section */}
        <div className="flex items-center gap-10">
          <Link href="/">
            <Image src={dashboard.logo} alt="logo" />
          </Link>

          <div className="flex gap-4 items-center">
            {links.map((item) => {
              const active = pathName === item.href;
              return (
                <NavLink
                  key={item.id}
                  label={item.label}
                  href={item.href}
                  icon={<item.icon active={active} />}
                  active={active}
                />
              );
            })}
          </div>
        </div>

        {/* Navigation buttons */}
        {/* <div className="flex items-center space-x-4">
          <DashboardButton />
          <NavbarProfileButton />
        </div> */}

        <div className="flex gap-2 items-center">
          <div className="w-[32px] h-[32px] border border-[#0b0b0b] rounded-md flex items-center justify-center">
            <Misc />
          </div>
          <div className="w-[32px] h-[32px] border border-[#444] rounded-md flex items-center justify-center">
            <Notification />
          </div>
          <div className="w-[32px] h-[32px] overflow-hidden rounded-md flex items-center justify-center cursor-pointer">
            <NavbarProfileButton>
              <ProfileIcon />
            </NavbarProfileButton>
          </div>
        </div>
      </div>
    </nav>
  );
};

// apps/fomoed/src/lib/comps/NewNavbar/NavBar.svelte
<script>
	import { page } from '$app/stores';
	import ProfileButton from './ProfileButton.svelte';
	import DashboardButton from './DashboardButton.svelte';
	import NewNavbarLogo from '../NewNavbarLogo/NewNavbarLogo.svelte';
	// import { toast } from '@zerodevx/svelte-toast';
	import toast from 'svelte-5-french-toast';

	function handleComingSoon() {
		toast('Coming Soon', {
			icon: '⏳'
		});
	}

	// You can add props here if needed, for example:
	// let { activePage } = $props();

	$: currentPath = $page.url.pathname;
	let scrollY = 0;
</script>

<div class="fixed top-0 w-full z-[999] -desktop:bg-[50%_50%]">
	<div class="relative overflow-hidden p-[1px] max-w-[550px] mx-auto w-full mt-3 rounded-2xl">
		<div class="gradient_border_tab"></div>

		<nav class="mx-auto px-6 py-[14px] bg-[#000] relative rounded-2xl">
			<div class="flex items-center justify-between w-full">
				<div class="flex items-center gap-6">
					<a href="/">
						<img src="/icons/small-logo.svg" alt="" />
					</a>

					<div class="flex items-center gap-4">
						<a href="/dashboard">
							<p
								class={`text-base font-semibold leading-[135%] ${currentPath === '/dashboard' ? 'text-white' : 'text-[#9b9b9b]'}`}
							>
								Dashboard
							</p>
						</a>

						<a href="/news">
							<p
								class={`text-base font-semibold leading-[135%] ${currentPath === '/news' ? 'text-white' : 'text-[#9b9b9b]'}`}
							>
								News
							</p>
						</a>

						<button type="button" on:click={handleComingSoon}>
							<p class="text-[#9b9b9b] text-base font-semibold leading-[135%] cursor-pointer">
								Signals
							</p>
						</button>
					</div>
				</div>

				<div class="">
					<ProfileButton></ProfileButton>
				</div>
			</div>
		</nav>
	</div>
</div>

<style>
	.gradient_border_tab {
		position: absolute;
		top: 0;
		bottom: 0;
		left: 0;
		right: 0;
		border-radius: inherit;
		/* background: conic-gradient(from 0deg at 50% 50%, #000000 0%, #666666 50%, #000000 100%); */
		/* background: conic-gradient(
      from 0deg at 50% 50%,
      #020100 0%,
      #342828 17%,
      #8b4332 35%,
      #8b2505 55%,
      #bd4618 72%,
      #f7984b 84%,
      #f7984b 100%
    ); */
		background: conic-gradient(
			from 0deg at 50% 50%,
			#020100 0%,
			#342828 17%,
			#8b4332 35%,
			#8b2505 55%,
			#bd4618 72%,
			#f7984b 84%,
			#f7984b 100%
		);
		background: linear-gradient(
			to bottom,
			#020100 0%,
			#342828 1%,
			#8b4332 35%,
			#8b2505 55%,
			#bd4618 72%,
			#f7984b 84%,
			#f7984b 100%
		);
		/* inset: -10000%; */
		pointer-events: none;
		opacity: 0.4;
	}
</style>
