// apps/dashboard/src/components/widgets/cignals/cignals-chart.tsx
"use client";
import { CignalsChart } from "@/charts/cignals-chart/cignalsChart";
import { CignalsChartDataProviderAPI } from "@/charts/cignals-chart/cignalsChartDataProvider";
import {
  CignalsChartOptions,
  ParsedCignalsInstrumentArray,
} from "@/charts/cignals-chart/types";
import { capitalizeFirst, cn } from "@/lib/utils";
import React, { useEffect, useRef, useState } from "react";
import CignalsModal from "./cignals-modal";

interface IProps {
  modalOpen: boolean;
  onClose: () => void;
}

const CignalsChartComp = (props: IProps) => {
  const { modalOpen, onClose } = props;
  const canvasRef = useRef<HTMLCanvasElement>(null);

  const chartRef = useRef<CignalsChart | null>(null);

  const [chartOptions, setChartOptions] = useState<CignalsChartOptions | null>(
    null
  );
  const [availableInstruments, setAvailableInstruments] =
    useState<ParsedCignalsInstrumentArray>([]);

  const [connsectionStatus, setConnectionStatus] = useState("disconnected");

  const onSocketConnecting = () => {
    console.log("Connecting to socket...");
    setConnectionStatus("connecting");
  };
  const onSocketDisconnected = () => {
    console.log("Socket disconnected");
    setConnectionStatus("disconnected");
  };
  const onSocketConnected = () => {
    console.log("Socket connected");
    setConnectionStatus("connected");
  };

  async function refreshAvailableInstruments() {
    const dataProvider = new CignalsChartDataProviderAPI();
    const currInstruments = await dataProvider.fetchInstruments();
    setAvailableInstruments(currInstruments);
  }

  useEffect(() => {
    if (!canvasRef.current) return;

    const provider = new CignalsChartDataProviderAPI();

    chartRef.current = new CignalsChart({
      canvas: canvasRef.current,
      dataProvider: provider,
      onSocketConnecting: onSocketConnecting,
      onSocketDisconnected: onSocketDisconnected,
      onSocketConnected: onSocketConnected,
    });
    chartRef.current.autoAdjustDatapointWidth();
    chartRef.current.refreshData();
    setChartOptions(chartRef.current.options);

    refreshAvailableInstruments();
  }, []);

  const handleSave = (newOptions: CignalsChartOptions) => {
    console.log("Saving new options", newOptions);
    if (!chartRef.current) return;
    chartRef.current.options = newOptions;
    setChartOptions(chartRef.current.options);
    onClose();
  };

  return (
    <div className="relative flex flex-col w-full h-full">
      {modalOpen && chartOptions ? (
        <CignalsModal
          availableInstruments={availableInstruments}
          onClose={onClose}
          onSave={handleSave}
          originalOptions={chartOptions}
        />
      ) : null}
      <div className="flex-grow">
        <canvas className="w-full h-full touch-none" ref={canvasRef}></canvas>
      </div>
      <div className="absolute top-0 left-4 flex items-center gap-1 mt-4 bg-[#1C1C1C] rounded-[6px] px-2 py-1">
        <div
          className={cn("w-2 h-2 rounded-full", {
            "bg-[#399F57]": connsectionStatus === "connected",
            "bg-[#FFB800]": connsectionStatus === "connecting",
            "bg-[#FF3D3D]": connsectionStatus === "disconnected",
          })}
        />
        <p className="text-[#9B9FA4] text-xs font-semibold ">
          {capitalizeFirst(connsectionStatus)}
        </p>
      </div>
    </div>
  );
};

export default CignalsChartComp;

// apps/fomoed/src/lib/comps/dashboard/widgets/CignalsChart/CignalsChart.svelte
<script lang="ts">
	import CignalsChartSettingsPopup from '$lib/comps/popups/CignalsChartSettingsPopup.svelte';
	import type { CignalsChartOptions, ParsedCignalsInstrumentArray } from '$lib/types';
	import type { SocketStatus } from '$ts/types';
	import { capitalize } from 'lodash-es';
	import { CignalsChart } from './cignalsChart';
	import { CignalsChartDataProviderAPI } from './cignalsChartDataProvider';
	import { mount, onDestroy, unmount } from 'svelte';
	import AdjustmentHorizontal from '$lib/icons/AdjustmentHorizontal.svelte';

	let props: { isFullscreen: boolean } = $props();

	let canvas: HTMLCanvasElement | null = $state(null);

	let dataProvider = new CignalsChartDataProviderAPI();
	let chart: CignalsChart | null = null;
	let availableInstruments: ParsedCignalsInstrumentArray = $state([]);

	$effect(() => {
		if (!canvas) return;

		const provider = new CignalsChartDataProviderAPI();

		chart = new CignalsChart({
			canvas,
			dataProvider: provider,
			onSocketConnecting: onSocketConnecting,
			onSocketDisconnected: onSocketDisconnected,
			onSocketConnected: onSocketConnected
		});
		chart.autoAdjustDatapointWidth();
		chart.refreshData();
		chartOptions = chart.options;

		refreshAvailableInstruments();
	});

	onDestroy(() => {
		chart?.destroy();
	});

	async function refreshAvailableInstruments() {
		availableInstruments = await dataProvider.fetchInstruments();
	}

	function onSave(newOptions: CignalsChartOptions) {
		if (!chart) {
			throw new Error('Chart not initialized');
		}

		if (!chartOptions) {
			throw new Error('Chart options are null');
		}

		chart.options = newOptions;
		chartOptions = chart.options;

		onPopupClose();
	}

	let chartOptions: CignalsChartOptions | null = $state(null);

	let settingsPopupComponent: CignalsChartSettingsPopup | null = null;

	function openPopup() {
		chartOptions = chart!.options;

		settingsPopupComponent = mount(CignalsChartSettingsPopup, {
			target: document.body,
			props: {
				origOptions: chartOptions,
				onSave,
				onCancel: onPopupClose,
				availableInstruments
			}
		});
	}

	onDestroy(() => {
		onPopupClose();
	});

	$inspect(settingsPopupComponent);

	function onPopupClose() {
		if (!settingsPopupComponent) {
			console.log('return');
			return;
		}

		unmount(settingsPopupComponent);
		settingsPopupComponent = null;
	}

	let selectedInstrument = $derived(
		availableInstruments.find((i) => i.id === chartOptions?.instrument.id) || null
	);

	$inspect(selectedInstrument);

	let selectedInstrumentTitle = $derived(
		selectedInstrument
			? (selectedInstrument?.base_currency + '/' + selectedInstrument?.quote_currency).toUpperCase()
			: null
	);

	// Socket status handlers
	let socketStatus: SocketStatus = $state('disconnected');

	function onSocketConnecting() {
		socketStatus = 'connecting';
	}

	function onSocketConnected() {
		socketStatus = 'connected';
	}

	function onSocketDisconnected() {
		socketStatus = 'disconnected';
	}
</script>

<div class="w-full h-full relative">
	<canvas class="absolute w-full h-full touch-none" bind:this={canvas}> </canvas>

	<!-- Toolbar -->
	<div
		class="absolute inset-x-0 top-0 px-2 py-2 flex gap-x-3 items-center bg-black/20 backdrop-blur-md"
	>
		<!-- Settings button -->
		<button
			onclick={openPopup}
			class="rounded-xl border border-white border-opacity-30 p-2 hover:bg-white/10 duration-100 active:brightness-50"
		>
			<div class="w-6 h-6">
				<AdjustmentHorizontal />
			</div>
		</button>

		<!-- Instrument info -->
		<div>
			{#if chartOptions}
				<div class="font-semibold">{selectedInstrumentTitle}</div>
			{/if}
		</div>

		<div class="flex-grow"></div>

		<!-- Socket status -->
		<div
			class="text-white font-semibold text-xs duration-200 {props.isFullscreen
				? 'pr-[4.5rem]'
				: 'pr-4'}"
			class:_connecting={socketStatus === 'connecting'}
			class:_connected={socketStatus === 'connected'}
			class:_disconnected={socketStatus === 'disconnected'}
		>
			{capitalize(socketStatus)}
		</div>
	</div>
</div>

<style>
	._connected {
		color: #00ff00;
	}

	._connecting {
		color: #ffff00;
	}

	._disconnected {
		color: #ff0000;
	}
</style>
