// apps/fomoed/src/lib/comps/buttons/DashboardButton.svelte
<script lang="ts">
	import Dashboard from '$lib/icons/Dashboard.svelte';
	import { mobileMenuOpen } from '$lib/stores/ui';
	import { auth_email, auth_user } from '$lib/stores/user';
</script>

<a
	onclick={() => mobileMenuOpen.set(false)}
	href="/"
	class="{$auth_user
		? 'h-[52px]'
		: 'h-[50px]'} bg-[#13100F] inline-flex justify-center font-paralucent font-medium text-xs border border-[#FFFFFF1A] rounded-[8px] px-[12px] items-center gap-x-[5px]"
>
	<span class="-translate-y-[2px]">
		<Dashboard />
	</span>

	Dashboard
</a>

// apps/dashboard/src/components/ui/dashboardButton.tsx
import React from "react";
import Link from "next/link";
import DashboardIcon from "../icons/DashboardIcon";

const DashboardButton: React.FC = () => {
    return (
        <Link
            href="/"
            className={`
            px-4 h-[40px] transition-colors rounded-full border
            border-[#2B2B2B] font-inter font-semibold inline-flex
            items-center gap-x-2 text-sm text-white`}
        >
            <DashboardIcon />

            <div className="-desktop:hidden">Dashboard</div>
        </Link>
    );
};

export default DashboardButton;
