// apps/fomoed/src/lib/comps/NewNavbar/DashboardButton.svelte
<script>
	import DashboardIcon from '$lib/icons/DashboardIcon.svelte';

	// You can add props here if needed, for example:
	// let { activePage } = $props();
</script>

<a
	href="/dashboard"
	class="px-4 h-[40px] transition-colors rounded-full border border-[#2B2B2B] font-inter font-semibold inline-flex items-center gap-x-2 text-sm"
>
	<DashboardIcon />

	<div class="-desktop:hidden">Dashboard</div>
</a>

// apps/dashboard/src/components/ui/dashboardButton.tsx
import React from "react";
import Link from "next/link";
import DashboardIcon from "../icons/DashboardIcon";

const DashboardButton: React.FC = () => {
    return (
        <Link
            href="/"
            className={`
            px-4 h-[40px] transition-colors rounded-full border
            border-[#2B2B2B] font-inter font-semibold inline-flex
            items-center gap-x-2 text-sm text-white`}
        >
            <DashboardIcon />

            <div className="-desktop:hidden">Dashboard</div>
        </Link>
    );
};

export default DashboardButton;
